from fpdf import FPDF
import pandas as pd

# Load the summary table
df = pd.read_csv("plgrkt_identity_summary.csv")

class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, "PLGRKT Gene Conservation Across Birds", ln=True, align="C")
        self.set_font("Arial", "", 12)
        self.cell(0, 10, "Generated by Swasti | IISER Bhopal", ln=True, align="C")
        self.ln(10)

    def chapter_title(self, title):
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, title, ln=True, align="L")
        self.ln(4)

    def chapter_body(self, text):
        self.set_font("Arial", "", 11)
        self.multi_cell(0, 8, text)
        self.ln()

    def add_image(self, path, w=170):
        self.image(path, x=20, w=w)
        self.ln()

    def add_table(self, dataframe):
        self.set_font("Arial", "B", 11)
        self.cell(80, 10, "Species", 1)
        self.cell(40, 10, "% Identity", 1)
        self.cell(40, 10, "Gene Status", 1)
        self.ln()
        self.set_font("Arial", "", 11)
        for i, row in dataframe.iterrows():
            status = (
                "Conserved" if row["%Identity"] >= 90
                else "Partial" if row["%Identity"] >= 50
                else "Lost"
            )
            self.cell(80, 10, row["Species"], 1)
            self.cell(40, 10, f'{row["%Identity"]:.1f}%', 1)
            self.cell(40, 10, status, 1)
            self.ln()

# Create PDF
pdf = PDF()
pdf.add_page()
pdf.chapter_title("Overview")
pdf.chapter_body(
    "This report summarizes the conservation of the PLGRKT gene across various bird species. "
    "Results are based on BLAST alignment of duck PLGRKT against the genome of each species."
)
pdf.chapter_title("Bar Graph: Identity Comparison")
pdf.add_image("PLGRKT_colored_barplot.png")
pdf.chapter_title("Table: % Identity and Gene Status")
pdf.add_table(df)

# Output
pdf.output("PLGRKT_Gene_Loss_Report.pdf")
print("✅ PDF report generated → PLGRKT_Gene_Loss_Report.pdf")
